Allow one to use dev & prerelease, Allow one to specify a artifact to use and some other minor changes (#68)
* Allow one to use dev & prerelease branch

* Use a single variable for the repo

* Fallback if no tags exist & enter the repo directory properly.

* Solve docker compose failing

* Allow one to specify a artifact to use.

diff --git a/.github/workflows/run_tests_runnerimprovements.yml b/.github/workflows/run_tests_runnerimprovements.yml
--- a/.github/workflows/run_tests_runnerimprovements.yml
+++ b/.github/workflows/run_tests_runnerimprovements.yml
@@ -53,7 +53,7 @@ on:
       branch:
         type: string
         required: false
-        description: "Which GMod branch to run your tests on. Must be: 'live' or 'x86-64'"
+        description: "Which GMod branch to run your tests on. Must be: 'live', 'prerelease', 'dev' or 'x86-64'"
         default: "live"
 
       gluatest-ref:
@@ -66,6 +66,15 @@ on:
         type: string
         required: false
         description: "An absolute path with custom files to copy to the server directly. Structure should match the contents of `garrysmod/`"
+
+      download-artifact:
+        type: string
+        required: false
+        description: "If specified it will download and setup the given artifact. It has to be a tar file that will be unpacked in the root directory."
+        default: ""
+
+env:
+  GLUA_REPO: https://github.com/CFC-Servers/GLuaTest
 
 jobs:
   test:
@@ -89,13 +98,16 @@ jobs:
         run: |
           cd $GITHUB_WORKSPACE
 
-          git clone --single-branch --branch ${{ inputs.gluatest-ref }} --depth 1 https://github.com/CFC-Servers/GLuaTest.git gluatest
+          git clone --single-branch --branch ${{ inputs.gluatest-ref }} --depth 1 ${{ env.GLUA_REPO }}.git gluatest
 
+          cd gluatest
           git fetch --quiet --tags
-          latest="$(git describe --tags `git rev-list --tags --max-count=1`)"
+
+          latest=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "0.00")
           echo "Latest Tag: $latest"
           echo "LATEST_TAG=$latest" >> $GITHUB_OUTPUT
 
+          cd ../
           cd $GITHUB_WORKSPACE
 
       - name: Prepare the override directory
@@ -126,7 +138,7 @@ jobs:
             # The repo is likely an addon
             dest="$GITHUB_WORKSPACE/garrysmod_override/addons/project/"
           else
-            echo "::error title=Unknown project structure!::Please report this: https://github.com/CFC-Servers/GLuaTest/issues"
+            echo "::error title=Unknown project structure!::Please report this: ${{ env.GLUA_REPO }}/issues"
             exit 1
           fi
 
@@ -138,15 +150,22 @@ jobs:
         run: |
           rsync --verbose --archive ${{ inputs.custom-overrides }} $GITHUB_WORKSPACE/garrysmod_override/
 
+      - name: Download artifact
+        if: inputs.download-artifact != ''
+        uses: actions/download-artifact@v4
+        with:
+          path: ${{ github.workspace }}/gluatest/docker/_gluatest_artifacts/
+          name: "${{ inputs.download-artifact }}"
+
       - name: Build GLuaTest
         env:
           REQUIREMENTS: "${{ github.workspace }}/project/${{ inputs.requirements }}"
           CUSTOM_SERVER_CONFIG: "${{ github.workspace }}/project/${{ inputs.server-cfg }}"
           PROJECT_DIR: "${{ github.workspace }}/garrysmod_override"
-
         run: |
           cd $GITHUB_WORKSPACE/gluatest/docker
-          docker build --build-arg="GMOD_BRANCH=${{ inputs.branch }}" --build-arg="GLUATEST_REF=${{ inputs.gluatest-ref }}" --tag ghcr.io/cfc-servers/gluatest:latest .
+          mkdir -p _gluatest_artifacts
+          docker build --build-arg="GMOD_BRANCH=${{ inputs.branch }}" --build-arg="GLUATEST_REPO=${{ env.GLUA_REPO }}.git" --build-arg="GLUATEST_REF=${{ inputs.gluatest-ref }}" --tag ghcr.io/cfc-servers/gluatest:latest .
 
       - name: Run GLuaTest
         env:
@@ -159,8 +178,8 @@ jobs:
           SSH_PRIVATE_KEY: "${{ inputs.ssh-private-key }}"
           GITHUB_TOKEN: "${{ inputs.github-token }}"
           TIMEOUT: "${{ inputs.timeout }}"
-
         run: |
+          cd $GITHUB_WORKSPACE/gluatest/docker
           docker compose up --pull never --no-log-prefix --exit-code-from runner
           exitstatus=$?
 
